<?php

// DEFINE WIDGETS
$widgets = array (
    array('Acre', 'text', ['fontSize' => '6.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'AC', 'default'),
    array('AL', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'AL', 'default'),
    array('Amapá', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'AP', 'default'),
    array('Amazonas', 'text', ['fontSize' => '7.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'AM', 'default'),
    array('Bahia', 'text', ['fontSize' => '6.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'BA', 'default'),
    array('Ceará', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'CE', 'default'),
    array('DF', 'text', ['fontSize' => '5.3'], '', 0, 0, 600, 'var(--widget-text-color)', 'DF', 'default'),
    array('ES', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'ES', 'default'),
    array('Goiás', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'GO', 'default'),
    array('Maranhão', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'MA', 'default'),
    array('Mato Grosso', 'text', ['fontSize' => '6.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'MT', 'default'),
    array('Mato Grosso do Sul', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'MS', 'default'),
    array('Minas Gerais', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'MG', 'default'),
    array('Pará', 'text', ['fontSize' => '7.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'PA', 'default'),
    array('PB', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'PB', 'default'),
    array('Paraná', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'PR', 'default'),
    array('PE', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'PE', 'default'),
    array('Piauí', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'PI', 'default'),
    array('RJ', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'RJ', 'default'),
    array('RN', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'RN', 'default'),
    array('Rio Grande do Sul', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'RS', 'default'),
    array('Rondônia', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'RO', 'default'),
    array('Roraima', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'RR', 'default'),
    array('SC', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'SC', 'default'),
    array('São Paulo', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'SP', 'default'),
    array('SE', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'SE', 'default'),
    array('Tocantins', 'text', ['fontSize' => '5.5'], '', 0, 0, 600, 'var(--widget-text-color)', 'TO', 'default'),
);