<?php

// Exemplo de uso para $add_widget_fields
$estados = [
    'AC' => 'ACRE',
    'AL' => 'ALAGOAS',
    'AP' => 'AMAPÁ',
    'AM' => 'AMAZONAS',
    'BA' => 'BAHIA',
    'CE' => 'CEARÁ',
    'DF' => 'DISTRITO FEDERAL',
    'ES' => 'ESPÍRITO SANTO',
    'GO' => 'GOIÁS',
    'MA' => 'MARANHÃO',
    'MG' => 'MINAS GERAIS',
    'MS' => 'MATO GROSSO DO SUL',
    'MT' => 'MATO GROSSO',
    'PA' => 'PARÁ',
    'PB' => 'PARAÍBA',
    'PE' => 'PERNAMBUCO',
    'PI' => 'PIAUÍ',
    'PR' => 'PARANÁ',
    'RJ' => 'RIO DE JANEIRO',
    'RN' => 'RIO GRANDE DO NORTE',
    'RO' => 'RONDÔNIA',
    'RR' => 'RORAIMA',
    'RS' => 'RIO GRANDE DO SUL',
    'SC' => 'SANTA CATARINA',
    'SE' => 'SERGIPE',
    'SP' => 'SÃO PAULO',
    'TO' => 'TOCANTINS',
];
?>

<?php
$add_widget_fields = [
    [
        'label' => 'Conteúdo',
        'type' => 'text',
        'required' => true,
        'placeholder' => 'Conteúdo',
        'name' => 'content',
        'value' => '',
        'id' => 'widget-name',
        'class' => 'widget-content',
    ],
    [
        'label' => 'Tipo',
        'type' => 'select',
        'required' => true,
        'placeholder' => 'Tipo',
        'name' => 'type',
        'value' => '',
        'id' => 'widget-type',
        'class' => 'widget-type',
        'options' => [
                'text' => 'Texto',
                'image' => 'Imagem',
        ],
    ],
    [
        'label' => 'Opções',
        'type' => 'text',
        'required' => true,
        'placeholder' => 'Opções',
        'name' => 'options',
        'value' => '',
        'id' => 'widget-options',
        'class' => 'widget-options',
    ],
    [
        'label' => 'Link',
        'type' => 'text',
        'required' => true,
        'placeholder' => 'Link',
        'name' => 'link',
        'value' => '',
        'id' => 'widget-link',
        'class' => 'widget-link',
    ],
    [
        'label' => 'Posição X',
        'type' => 'text',
        'required' => true,
        'placeholder' => 'Posição X',
        'name' => 'x',
        'value' => '',
        'id' => 'widget-x',
        'class' => 'widget-x',
    ],
    [
        'label' => 'Posição Y',
        'type' => 'text',
        'required' => true,
        'placeholder' => 'Posição Y',
        'name' => 'y',
        'value' => '',
        'id' => 'widget-y',
        'class' => 'widget-y',
    ],
    [
        'label' => 'Peso',
        'type' => 'text',
        'required' => true,
        'placeholder' => 'Peso',
        'name' => 'weight',
        'value' => '',
        'id' => 'widget-weight',
        'class' => 'widget-weight',
    ],
    [
        'label' => 'Cor',
        'type' => 'color',
        'required' => true,
        'placeholder' => 'Cor',
        'name' => 'color',
        'value' => '',
        'id' => 'widget-color',
        'class' => 'widget-color',
    ],
    [
        'label' => 'Código do Estado',
        'type' => 'select',
        'required' => true,
        'placeholder' => 'Código do Estado',
        'name' => 'state_code',
        'value' => '',
        'id' => 'widget-state-code',
        'class' => 'widget-state-code',
        'options' => $estados,
    ],
   
    [
        'label' => 'Classe CSS',
        'type' => 'text',
        'required' => true,
        'placeholder' => 'Classe CSS',
        'name' => 'custom_class',
        'value' => '',
        'id' => 'widget-custom-class',
        'class' => 'widget-custom-class',
    ],
    [
        'label' => 'Salvar',
        'type' => 'button',
        'required' => true,
        'placeholder' => 'Salvar alterações',
        'name' => 'save',
        'value' => '',
        'id' => 'add-widget',
        'class' => 'reload-map-button button emu-button emu-button-default',
    ],
];

if (!is_array($widgets)) {
    $widgets = [];
}

function get_widgets_index($widget, $index) {


    $remove_widget_fields = [
        [
            'id'          => 'widget-name_'.$index,
            'label'       => 'Conteúdo',
            'type'        => 'text',
            'placeholder' => 'Conteúdo',
            'name'        => 'widgets[' . $index . '][0]',
            'value'       => $widget[0],
            'readonly'    => true,
        ],
        [
            'id'          => 'widget-type_'.$index,
            'label'       => 'Tipo',
            'type'        => 'select',
            'placeholder' => 'Tipo',
            'name'        => 'widgets[' . $index . '][1]',
            'value'       => $widget[1],    
            'readonly'    => true,
            'options' => [
                'text' => 'Texto',
                'image' => 'Imagem',
            ],
        ],
        [
            'id'          => 'widget-options_'.$index,
            'label'       => 'Opções',
            'type'        => 'text',
            'placeholder' => 'Opções',
            'name'        => 'widgets[' . $index . '][2]',
            'value'       => $widget[2],
            'readonly'    => true,
        ],
        [
            'id'          => 'widget-link_'.$index,
            'label'       => 'Link',
            'type'        => 'text',
            'placeholder' => 'Link',
            'name'        => 'widgets[' . $index . '][3]',
            'value'       => $widget[3],
            'readonly'    => true,
        ],
        [
            'id'          => 'widget-x_'.$index,
            'label'       => 'Posição X',
            'type'        => 'text',
            'placeholder' => 'Posição X',
            'name'        => 'widgets[' . $index . '][4]',
            'value'       => $widget[4],
            'readonly'    => true,
        ],
        [
            'id'          => 'widget-y_'.$index,
            'label'       => 'Posição Y',
            'type'        => 'text',
            'placeholder' => 'Posição Y',
            'name'        => 'widgets[' . $index . '][5]',
            'value'       => $widget[5],
            'readonly'    => true,
        ],
        [
            'id'          => 'widget-weight_'.$index,
            'label'       => 'Peso',
            'type'        => 'text',
            'placeholder' => 'Peso',
            'name'        => 'widgets[' . $index . '][6]',
            'value'       => $widget[6],
            'readonly'    => true,
        ],
        [
            'id'          => 'widget-color_'.$index,
            'label'       => 'Cor',
            'type'        => 'color',
            'placeholder' => 'Cor',
            'name'        => 'widgets[' . $index . '][7]',
            'value'       => $widget[7],
            'readonly'    => true,
        ],
        [
            'id'          => 'widget-state_code_'.$index,
            'label'       => 'Estado',
            'type'        => 'text',
            'placeholder' => 'Estado',
            'name'        => 'widgets[' . $index . '][8]',
            'value'       => $widget[8],
            'readonly'    => true,
        ],
        [
            'id'          => 'widget-custom_class_'.$index,
            'label'       => 'Classe CSS',
            'type'        => 'text',
            'placeholder' => 'Classe CSS',
            'name'        => 'widgets[' . $index . '][9]',
            'value'       => $widget[9],
            'readonly'    => true,
        ],
        [
            'id'          => 'remove-widget_'.$index,
            'label'       => 'Remover',
            'type'        => 'button',
            'class'       => 'reload-map-button remove-widget button emu-button emu-button-danger',
            'placeholder' => 'Remover',
            'name'        => 'remove_widget',
            'value'       => $widget[0],
            'readonly'    => true,
        ],
    ];

    return $remove_widget_fields;

}